### ISSUE TITLE
gp: collect string global prevalence data

### ISSUE THREAD

**Issue by williballenthin** [fireeye/flare-floss#713]
```[tasklist]
### Tasks
- [ ] gp: collect files from windows xp image
- [ ] gp: collect files from windows 7 image
- [ ] gp: collect files from windows 11 image
- [ ] gp: collect files from ubuntu image
- [ ] gp: collect files from macOS image
- [ ] gp: collect files from cygwin
- [ ] https://github.com/mandiant/flare-floss/issues/722
```

**Comment by mr-tz** [comment]
There may be value in including meta data (like offsets and associated section) for data that we generate from scratch.

So instead of knowing "stringX is common", we would know "stringX is common at offsetY/in sectionZ".

**Comment by williballenthin** [comment]
for NSRL files, we can use the published diskprints https://www.nist.gov/itl/ssd/software-quality-group/national-software-reference-library-nsrl/nsrl-subprojects/diskprints
and extract hashes of .exe and .dll file paths and fetch those from VT/etc. and extract hashes.

**Comment by williballenthin** [comment]
we should pull from files that we expect to use multiple compilers, too, such as cygwin. and maybe pull from non-windows systems, like linux and macos, to get gcc and llvm toolchain coverage.

**Comment by williballenthin** [comment]
for windows files we can enumerate and acquire them via here: https://m417z.com/Introducing-Winbindex-the-Windows-Binaries-Index/

**Comment by c-urly** [comment]
If we want to add ELF,MACH-O layout support in QS we will also need to create database with elf binaries/MACH-O and malwares correct?

**Comment by williballenthin** [comment]
Strictly speaking, no.

But, I do think the databases would be much more useful with this information.
